# Generated by Django 3.1.2 on 2020-10-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
